# Generated by Django 5.1.5 on 2025-01-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('airport_name', models.CharField(max_length=255)),
                ('faa', models.CharField(blank=True, max_length=3, null=True)),
                ('iata', models.CharField(blank=True, max_length=3, null=True)),
                ('icao', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
    ]
