# Generated by Django 5.1.5 on 2025-02-16 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('airport_name', models.CharField(max_length=255)),
                ('faa', models.CharField(blank=True, max_length=3, null=True)),
                ('iata', models.CharField(blank=True, max_length=3, null=True)),
                ('icao', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='FlightAPI.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('card_number', models.CharField(max_length=16)),
                ('card_expiry_month', models.IntegerField()),
                ('card_expiry_year', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('cardholder_name', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='FlightAPI.customer')),
            ],
        ),
        migrations.CreateModel(
            name='FlightBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(blank=True, max_length=12, unique=True)),
                ('flight_cancellation_protection', models.BooleanField(default=False)),
                ('sms_support', models.BooleanField(default=False)),
                ('baggage_protection', models.BooleanField(default=False)),
                ('premium_support', models.BooleanField(default=False)),
                ('total_refund_protection', models.BooleanField(default=False)),
                ('payble_amount', models.FloatField(verbose_name='Payable amt.($)')),
                ('flight_name', models.CharField(max_length=200)),
                ('departure_iata', models.CharField(max_length=4)),
                ('arrival_iata', models.CharField(max_length=4)),
                ('departure_date', models.DateTimeField()),
                ('arrival_date', models.DateTimeField()),
                ('agent', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='FlightAPI.customer')),
                ('passengers', models.ManyToManyField(related_name='flights', to='FlightAPI.passenger')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FlightAPI.payment', verbose_name='payment by')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(help_text='Upload the PDF ticket for the customer.', upload_to='media/tickets/')),
                ('message', models.TextField(blank=True, help_text='Optional message to be sent with the ticket.', null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='FlightAPI.customer')),
            ],
            options={
                'verbose_name': 'Send Ticket',
                'verbose_name_plural': 'Send Tickets',
            },
        ),
    ]
