# Generated by Django 5.1.5 on 2025-03-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('message', models.TextField(verbose_name='Message')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
            ],
        ),
    ]
