"""
Django settings for FlightCRM project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xcfh484+^5mp8a%117h6kigwac1m8tso=f4p%84bqm5wpg$x3!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['localhost', '127.0.0.1','crm.valueutickets.com']

# Set timezone to Eastern Standard Time (EST)
TIME_ZONE = 'America/New_York'

USE_I18N = True
USE_TZ = True


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'FlightAPI',
    'corsheaders',
    'rangefilter',
    'rest_framework_simplejwt',
]

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# Security settings
SECURE_CONTENT_TYPE_NOSNIFF = True  # Prevents browsers from MIME-sniffing files
SECURE_BROWSER_XSS_FILTER = True    # Enables XSS filtering by the browser

# Enforce HTTPS
SECURE_SSL_REDIRECT = True
SECURE_HSTS_SECONDS = 31536000  # 1 year; adjust based on preference
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Clickjacking protection
X_FRAME_OPTIONS = 'DENY'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'mail.valueutickets.com'
EMAIL_PORT = 465  
EMAIL_USE_SSL = True
EMAIL_HOST_USER = 'customerservice@valueutickets.com'
EMAIL_HOST_PASSWORD = r"}(UM93%Y(5T^" 
DEFAULT_FROM_EMAIL = 'customerservice@valueutickets.com'
# Set EMAIL_USE_TLS = False since you're using SSL (port 465)
EMAIL_USE_TLS = False



CORS_ALLOWED_ORIGINS = [
    "http://localhost:7008",  # Allow Vue app to access API
    "https://valueutickets.com",
    "http://valueutickets.com"
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "OPTIONS",
]

CORS_ALLOW_HEADERS = [
    'authorization',
    'content-type',
    'x-requested-with',
]

ROOT_URLCONF = 'FlightCRM.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS':[],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'FlightCRM.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': "valueuti_valueuticket",  # Database name from environment variable
        'USER': 'valueuti_value',  # Database user from environment variable
        'PASSWORD': 'airtravelove',  # Database password from environment variable
        'HOST': "localhost",  # Database host from environment variable
        'PORT': 3306,  
    }
}


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',  # Database name from environment variable
#         # 'USER': 'root',  # Database user from environment variable
#         # 'PASSWORD': '9069076975',  # Database password from environment variable
#         # 'HOST': "localhost",  # Database host from environment variable
#         # 'PORT': 3306,  
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# settings.py

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]


STATIC_ROOT = BASE_DIR / 'staticfiles'

# STATICFILES_DIRS = [
#     BASE_DIR / 'Fligh' / 'FrontEnd' / 'static',
# ]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


JAZZMIN_SETTINGS = {
    "site_title": "Admin Portal",
    "site_header": "ValueuTickets CRM",
    "site_brand": "ValueuTickets",
    "welcome_sign": "Welcome to the ValueuTickets CRM",
    "search_model": "auth.User",
    "user_avatar": None,

    # UI Customizations
    "topmenu_links": [
        # Define other links here
    ],
    "icons": {
        "FlightAPI.Customer": "fas fa-road",
        "FlightAPI.Passenger": "fas fa-users",
        "FlightAPI.Payment": "fas fa-credit-card",
        "FlightAPI.FlightBooking": "fas fa-plane",
        "FlightAPI.SendTicket": "fas fa-ticket-alt",
        "admin.LogEntry": "fas fa-clipboard-list",
        "auth.User": "fas fa-user-tie",
        "auth.Group": "fas fa-building",
    },
    
}

# settings.py

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-navy",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": True,  # Removed border for a cleaner look
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False, 
    "sidebar_fixed": True,
    "sidebar": "sidebar-light-primary", 
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True, 
    "sidebar_nav_compact_style": True,  
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,  
    "theme": "darkly",  
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}


# DRF Configuration (if necessary)
# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': [
#         'rest_framework.authentication.BasicAuthentication',
#         'rest_framework.authentication.SessionAuthentication',
#     ],
#     'DEFAULT_PERMISSION_CLASSES': [
#         'rest_framework.permissions.IsAuthenticated',
#     ],
# }
